on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          show-progress: 'false'
      - uses: actions/cache@v4
        with:
          path: /root/.jbang
          key: $-jbang-$
          restore-keys: |
            $-jbang-
      - name: jbang
        uses: jbangdev/jbang-action@v0.117.1
        with:
          script: gcl.java
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          show-progress: 'false'
      - name: markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v17
        with:
          globs: |
            *.md
      - name: Lint CHANGELOG.md
        run: |
          # Install jbang
          curl -Ls https://sh.jbang.dev | bash -s - app setup
          export PATH=$PATH:$HOME/.jbang/bin

          # run heylogs verification
          jbang com.github.nbbrd.heylogs:heylogs-cli:0.7.2:bin check CHANGELOG.md > heylogs.txt || true

          # improve output
          sed -i 's/all-h2-contain-a-version/all-h2-contain-a-version (ignored)/' heylogs.txt

          cat heylogs.txt

          # exit 1 in case of error
          # We have 1 "valid" issue in CHANGELOG.md
          grep -q "4 problems" heylogs.txt || exit 1
