on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: /root/.jbang
          key: $-jbang-$
          restore-keys: |
            $-jbang-
      - name: jbang
        uses: jbangdev/jbang-action@v0.116.0
        with:
          script: gcl.java
