on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          show-progress: 'false'
      - uses: actions/cache@v4
        with:
          path: /root/.jbang
          key: $-jbang-$
          restore-keys: |
            $-jbang-
      - name: jbang
        uses: jbangdev/jbang-action@v0.115.0
        with:
          script: gcl.java
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}